# Generated by Django 3.0 on 2019-12-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_catalog', '0002_auto_20191218_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediapublish',
            options={'verbose_name': 'MediaPublish', 'verbose_name_plural': 'Media Publishes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='mediapublish',
            old_name='meida',
            new_name='media',
        ),
    ]
