# Generated by Django 2.2.9 on 2019-12-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_catalog', '0003_auto_20191218_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MediaUser',
        ),
        migrations.AlterModelOptions(
            name='mediapublish',
            options={'verbose_name': 'Media Publish', 'verbose_name_plural': 'Media Publishes'},
        ),
        migrations.AlterModelOptions(
            name='mediauser',
            options={'verbose_name': 'Media User', 'verbose_name_plural': 'Meida Users'},
        ),
    ]
